### ISSUE TITLE
Strange Mob Tracking Behavior

### ISSUE THREAD

**Issue by K-Mistele** [amistele/ascii-adventure#18]
Some strange mob tracking behavior, especially near player. Possibly a reversed x-direction in the AI, will look into farther.

**Comment by K-Mistele** [comment]
Problems: 
- [ ] Mob range needs to be extended across the board
- [ ] Mobs will not pursue player across terrain tiles, even if terrain is viable for them
- [ ] Weird bug occurs if player moves on top of monsters
    - [ ] re-work so players and mobs can't overlap, rather an attempt to constitutes an "attack" and does damage

**Comment by K-Mistele** [comment]
Found a fix thanks to @Michael-N, will be working on this soon.

**Comment by K-Mistele** [comment]
Player can no longer move on top of monsters

**Comment by K-Mistele** [comment]
Working on the last bug soon!

**Comment by K-Mistele** [comment]
@Michael-N switch to branch `mob-AI-gameplay-combat`. Code for mob chasing etc. is working, but the mobs aren't moving. One of the conditionals must be evaluating false. Any thoughts?

**Comment by K-Mistele** [comment]
Ha. Squashed it. It was checking to see if any mobs shared the x coordinate OR the y coordinate of where it was trying to move, and it was checking all the mobs in `world.monsters`. It was essentially colliding with itself. @Michael-N
